AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.lambda_handler  # The handler function in your Lambda code
      Runtime: python3.8              # Runtime for your Lambda (adjust as needed)
      CodeUri: ./src                  # Path to your Lambda function code
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          PARAM1: "value1"
