AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.lambda_handler
      Runtime: python3.8
      InlineCode: |
        exports.handler = async (event) => {
          console.log("Hello World!");
          return {
            statusCode: 200,
            body: JSON.stringify({
              message: 'Hello World from Inline Lambda!22',
            }),
          };
        };
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          PARAM1: "value1"
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  bedrockproxyy:
    Description: "Hello World Lambda Function ARN"
    Value: arn:aws:lambda:us-west-2:619071353516:function:bedrockproxyy