name: Deploy AWS SAM Application

on:
  push:
    branches:
      - main  # Trigger deployment on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu environment for the workflow

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python (if using Python for Lambda functions)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version (adjust as needed)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up AWS credentials (using GitHub Secrets)
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      # Step 5: Install AWS SAM CLI
      - name: Install AWS SAM CLI
        run: |
          curl --silent --location https://github.com/aws/aws-sam-cli/releases/download/v1.42.0/aws-sam-cli-linux-x86_64.zip -o sam-cli.zip
          unzip -q sam-cli.zip -d sam-cli
          sudo ./sam-cli/install --update

      # Step 6: Build the SAM application
      - name: Build the SAM application
        run: |
          sam build

      # Step 7: Deploy the SAM application to AWS
      - name: Deploy the SAM application
        run: |
          sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM --stack-name my-sam-stack62 --region us-west-2 --no-s3

